

name: Build and deploy JAR app to heroku Web App - tennis-stats-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
   name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

  deploy:
    runs-on: ruby:latest
    needs: build
      - name: Deploy to Heruko Web App
        uses: actions/checkout@v2
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'tennis-stats-api'
          heroku_email: "nazihasmat22@gmail.com"
